// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/cronn/app/conditions"
)

// ConditionCheckerMock is a mock implementation of service.ConditionChecker.
//
//	func TestSomethingThatUsesConditionChecker(t *testing.T) {
//
//		// make and configure a mocked service.ConditionChecker
//		mockedConditionChecker := &ConditionCheckerMock{
//			CheckFunc: func(conditionsMoqParam conditions.Config) (bool, string) {
//				panic("mock out the Check method")
//			},
//		}
//
//		// use mockedConditionChecker in code that requires service.ConditionChecker
//		// and then make assertions.
//
//	}
type ConditionCheckerMock struct {
	// CheckFunc mocks the Check method.
	CheckFunc func(conditionsMoqParam conditions.Config) (bool, string)

	// calls tracks calls to the methods.
	calls struct {
		// Check holds details about calls to the Check method.
		Check []struct {
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam conditions.Config
		}
	}
	lockCheck sync.RWMutex
}

// Check calls CheckFunc.
func (mock *ConditionCheckerMock) Check(conditionsMoqParam conditions.Config) (bool, string) {
	if mock.CheckFunc == nil {
		panic("ConditionCheckerMock.CheckFunc: method is nil but ConditionChecker.Check was just called")
	}
	callInfo := struct {
		ConditionsMoqParam conditions.Config
	}{
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(conditionsMoqParam)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedConditionChecker.CheckCalls())
func (mock *ConditionCheckerMock) CheckCalls() []struct {
	ConditionsMoqParam conditions.Config
} {
	var calls []struct {
		ConditionsMoqParam conditions.Config
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}
