// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/cronn/app/service/request"
)

// JobEventHandlerMock is a mock implementation of service.JobEventHandler.
//
//	func TestSomethingThatUsesJobEventHandler(t *testing.T) {
//
//		// make and configure a mocked service.JobEventHandler
//		mockedJobEventHandler := &JobEventHandlerMock{
//			OnJobCompleteFunc: func(req request.OnJobComplete)  {
//				panic("mock out the OnJobComplete method")
//			},
//			OnJobStartFunc: func(req request.OnJobStart)  {
//				panic("mock out the OnJobStart method")
//			},
//		}
//
//		// use mockedJobEventHandler in code that requires service.JobEventHandler
//		// and then make assertions.
//
//	}
type JobEventHandlerMock struct {
	// OnJobCompleteFunc mocks the OnJobComplete method.
	OnJobCompleteFunc func(req request.OnJobComplete)

	// OnJobStartFunc mocks the OnJobStart method.
	OnJobStartFunc func(req request.OnJobStart)

	// calls tracks calls to the methods.
	calls struct {
		// OnJobComplete holds details about calls to the OnJobComplete method.
		OnJobComplete []struct {
			// Req is the req argument value.
			Req request.OnJobComplete
		}
		// OnJobStart holds details about calls to the OnJobStart method.
		OnJobStart []struct {
			// Req is the req argument value.
			Req request.OnJobStart
		}
	}
	lockOnJobComplete sync.RWMutex
	lockOnJobStart    sync.RWMutex
}

// OnJobComplete calls OnJobCompleteFunc.
func (mock *JobEventHandlerMock) OnJobComplete(req request.OnJobComplete) {
	if mock.OnJobCompleteFunc == nil {
		panic("JobEventHandlerMock.OnJobCompleteFunc: method is nil but JobEventHandler.OnJobComplete was just called")
	}
	callInfo := struct {
		Req request.OnJobComplete
	}{
		Req: req,
	}
	mock.lockOnJobComplete.Lock()
	mock.calls.OnJobComplete = append(mock.calls.OnJobComplete, callInfo)
	mock.lockOnJobComplete.Unlock()
	mock.OnJobCompleteFunc(req)
}

// OnJobCompleteCalls gets all the calls that were made to OnJobComplete.
// Check the length with:
//
//	len(mockedJobEventHandler.OnJobCompleteCalls())
func (mock *JobEventHandlerMock) OnJobCompleteCalls() []struct {
	Req request.OnJobComplete
} {
	var calls []struct {
		Req request.OnJobComplete
	}
	mock.lockOnJobComplete.RLock()
	calls = mock.calls.OnJobComplete
	mock.lockOnJobComplete.RUnlock()
	return calls
}

// OnJobStart calls OnJobStartFunc.
func (mock *JobEventHandlerMock) OnJobStart(req request.OnJobStart) {
	if mock.OnJobStartFunc == nil {
		panic("JobEventHandlerMock.OnJobStartFunc: method is nil but JobEventHandler.OnJobStart was just called")
	}
	callInfo := struct {
		Req request.OnJobStart
	}{
		Req: req,
	}
	mock.lockOnJobStart.Lock()
	mock.calls.OnJobStart = append(mock.calls.OnJobStart, callInfo)
	mock.lockOnJobStart.Unlock()
	mock.OnJobStartFunc(req)
}

// OnJobStartCalls gets all the calls that were made to OnJobStart.
// Check the length with:
//
//	len(mockedJobEventHandler.OnJobStartCalls())
func (mock *JobEventHandlerMock) OnJobStartCalls() []struct {
	Req request.OnJobStart
} {
	var calls []struct {
		Req request.OnJobStart
	}
	mock.lockOnJobStart.RLock()
	calls = mock.calls.OnJobStart
	mock.lockOnJobStart.RUnlock()
	return calls
}
