FROM goreleaser/goreleaser:nightly as build

WORKDIR /build
ADD . /build

RUN goreleaser --snapshot --skip=publish --clean
RUN ls -la /build/.bin/*

FROM alpine
COPY --from=build /build/.bin/ /dist/
RUN \
    mkdir -p /artifacts && \
    cp /dist/*.gz /artifacts/ && \
    cp /dist/*.zip /artifacts/ && \
    cp /dist/*.txt /artifacts/ && \
    cp /dist/*.rpm /artifacts/ && \
    cp /dist/*.deb /artifacts/ && \
    ls -la /artifacts/*

CMD ["sleep", "100"]
