// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/cronn/app/service/request"
	"github.com/umputun/cronn/app/web/persistence"
)

// PersistenceMock is a mock implementation of web.Persistence.
//
//	func TestSomethingThatUsesPersistence(t *testing.T) {
//
//		// make and configure a mocked web.Persistence
//		mockedPersistence := &PersistenceMock{
//			CleanupOldExecutionsFunc: func(jobID string, limit int) error {
//				panic("mock out the CleanupOldExecutions method")
//			},
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			GetExecutionByIDFunc: func(execID int) (persistence.ExecutionInfo, error) {
//				panic("mock out the GetExecutionByID method")
//			},
//			GetExecutionByStartFunc: func(jobID string, start int64) (persistence.ExecutionInfo, error) {
//				panic("mock out the GetExecutionByStart method")
//			},
//			GetExecutionsFunc: func(jobID string, limit int) ([]persistence.ExecutionInfo, error) {
//				panic("mock out the GetExecutions method")
//			},
//			LoadJobsFunc: func() ([]persistence.JobInfo, error) {
//				panic("mock out the LoadJobs method")
//			},
//			RecordExecutionFunc: func(req request.RecordExecution) error {
//				panic("mock out the RecordExecution method")
//			},
//			SaveJobsFunc: func(jobs []persistence.JobInfo) error {
//				panic("mock out the SaveJobs method")
//			},
//		}
//
//		// use mockedPersistence in code that requires web.Persistence
//		// and then make assertions.
//
//	}
type PersistenceMock struct {
	// CleanupOldExecutionsFunc mocks the CleanupOldExecutions method.
	CleanupOldExecutionsFunc func(jobID string, limit int) error

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// GetExecutionByIDFunc mocks the GetExecutionByID method.
	GetExecutionByIDFunc func(execID int) (persistence.ExecutionInfo, error)

	// GetExecutionByStartFunc mocks the GetExecutionByStart method.
	GetExecutionByStartFunc func(jobID string, start int64) (persistence.ExecutionInfo, error)

	// GetExecutionsFunc mocks the GetExecutions method.
	GetExecutionsFunc func(jobID string, limit int) ([]persistence.ExecutionInfo, error)

	// LoadJobsFunc mocks the LoadJobs method.
	LoadJobsFunc func() ([]persistence.JobInfo, error)

	// RecordExecutionFunc mocks the RecordExecution method.
	RecordExecutionFunc func(req request.RecordExecution) error

	// SaveJobsFunc mocks the SaveJobs method.
	SaveJobsFunc func(jobs []persistence.JobInfo) error

	// calls tracks calls to the methods.
	calls struct {
		// CleanupOldExecutions holds details about calls to the CleanupOldExecutions method.
		CleanupOldExecutions []struct {
			// JobID is the jobID argument value.
			JobID string
			// Limit is the limit argument value.
			Limit int
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetExecutionByID holds details about calls to the GetExecutionByID method.
		GetExecutionByID []struct {
			// ExecID is the execID argument value.
			ExecID int
		}
		// GetExecutionByStart holds details about calls to the GetExecutionByStart method.
		GetExecutionByStart []struct {
			// JobID is the jobID argument value.
			JobID string
			// Start is the start argument value.
			Start int64
		}
		// GetExecutions holds details about calls to the GetExecutions method.
		GetExecutions []struct {
			// JobID is the jobID argument value.
			JobID string
			// Limit is the limit argument value.
			Limit int
		}
		// LoadJobs holds details about calls to the LoadJobs method.
		LoadJobs []struct {
		}
		// RecordExecution holds details about calls to the RecordExecution method.
		RecordExecution []struct {
			// Req is the req argument value.
			Req request.RecordExecution
		}
		// SaveJobs holds details about calls to the SaveJobs method.
		SaveJobs []struct {
			// Jobs is the jobs argument value.
			Jobs []persistence.JobInfo
		}
	}
	lockCleanupOldExecutions sync.RWMutex
	lockClose                sync.RWMutex
	lockGetExecutionByID     sync.RWMutex
	lockGetExecutionByStart  sync.RWMutex
	lockGetExecutions        sync.RWMutex
	lockLoadJobs             sync.RWMutex
	lockRecordExecution      sync.RWMutex
	lockSaveJobs             sync.RWMutex
}

// CleanupOldExecutions calls CleanupOldExecutionsFunc.
func (mock *PersistenceMock) CleanupOldExecutions(jobID string, limit int) error {
	if mock.CleanupOldExecutionsFunc == nil {
		panic("PersistenceMock.CleanupOldExecutionsFunc: method is nil but Persistence.CleanupOldExecutions was just called")
	}
	callInfo := struct {
		JobID string
		Limit int
	}{
		JobID: jobID,
		Limit: limit,
	}
	mock.lockCleanupOldExecutions.Lock()
	mock.calls.CleanupOldExecutions = append(mock.calls.CleanupOldExecutions, callInfo)
	mock.lockCleanupOldExecutions.Unlock()
	return mock.CleanupOldExecutionsFunc(jobID, limit)
}

// CleanupOldExecutionsCalls gets all the calls that were made to CleanupOldExecutions.
// Check the length with:
//
//	len(mockedPersistence.CleanupOldExecutionsCalls())
func (mock *PersistenceMock) CleanupOldExecutionsCalls() []struct {
	JobID string
	Limit int
} {
	var calls []struct {
		JobID string
		Limit int
	}
	mock.lockCleanupOldExecutions.RLock()
	calls = mock.calls.CleanupOldExecutions
	mock.lockCleanupOldExecutions.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *PersistenceMock) Close() error {
	if mock.CloseFunc == nil {
		panic("PersistenceMock.CloseFunc: method is nil but Persistence.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedPersistence.CloseCalls())
func (mock *PersistenceMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetExecutionByID calls GetExecutionByIDFunc.
func (mock *PersistenceMock) GetExecutionByID(execID int) (persistence.ExecutionInfo, error) {
	if mock.GetExecutionByIDFunc == nil {
		panic("PersistenceMock.GetExecutionByIDFunc: method is nil but Persistence.GetExecutionByID was just called")
	}
	callInfo := struct {
		ExecID int
	}{
		ExecID: execID,
	}
	mock.lockGetExecutionByID.Lock()
	mock.calls.GetExecutionByID = append(mock.calls.GetExecutionByID, callInfo)
	mock.lockGetExecutionByID.Unlock()
	return mock.GetExecutionByIDFunc(execID)
}

// GetExecutionByIDCalls gets all the calls that were made to GetExecutionByID.
// Check the length with:
//
//	len(mockedPersistence.GetExecutionByIDCalls())
func (mock *PersistenceMock) GetExecutionByIDCalls() []struct {
	ExecID int
} {
	var calls []struct {
		ExecID int
	}
	mock.lockGetExecutionByID.RLock()
	calls = mock.calls.GetExecutionByID
	mock.lockGetExecutionByID.RUnlock()
	return calls
}

// GetExecutionByStart calls GetExecutionByStartFunc.
func (mock *PersistenceMock) GetExecutionByStart(jobID string, start int64) (persistence.ExecutionInfo, error) {
	if mock.GetExecutionByStartFunc == nil {
		panic("PersistenceMock.GetExecutionByStartFunc: method is nil but Persistence.GetExecutionByStart was just called")
	}
	callInfo := struct {
		JobID string
		Start int64
	}{
		JobID: jobID,
		Start: start,
	}
	mock.lockGetExecutionByStart.Lock()
	mock.calls.GetExecutionByStart = append(mock.calls.GetExecutionByStart, callInfo)
	mock.lockGetExecutionByStart.Unlock()
	return mock.GetExecutionByStartFunc(jobID, start)
}

// GetExecutionByStartCalls gets all the calls that were made to GetExecutionByStart.
// Check the length with:
//
//	len(mockedPersistence.GetExecutionByStartCalls())
func (mock *PersistenceMock) GetExecutionByStartCalls() []struct {
	JobID string
	Start int64
} {
	var calls []struct {
		JobID string
		Start int64
	}
	mock.lockGetExecutionByStart.RLock()
	calls = mock.calls.GetExecutionByStart
	mock.lockGetExecutionByStart.RUnlock()
	return calls
}

// GetExecutions calls GetExecutionsFunc.
func (mock *PersistenceMock) GetExecutions(jobID string, limit int) ([]persistence.ExecutionInfo, error) {
	if mock.GetExecutionsFunc == nil {
		panic("PersistenceMock.GetExecutionsFunc: method is nil but Persistence.GetExecutions was just called")
	}
	callInfo := struct {
		JobID string
		Limit int
	}{
		JobID: jobID,
		Limit: limit,
	}
	mock.lockGetExecutions.Lock()
	mock.calls.GetExecutions = append(mock.calls.GetExecutions, callInfo)
	mock.lockGetExecutions.Unlock()
	return mock.GetExecutionsFunc(jobID, limit)
}

// GetExecutionsCalls gets all the calls that were made to GetExecutions.
// Check the length with:
//
//	len(mockedPersistence.GetExecutionsCalls())
func (mock *PersistenceMock) GetExecutionsCalls() []struct {
	JobID string
	Limit int
} {
	var calls []struct {
		JobID string
		Limit int
	}
	mock.lockGetExecutions.RLock()
	calls = mock.calls.GetExecutions
	mock.lockGetExecutions.RUnlock()
	return calls
}

// LoadJobs calls LoadJobsFunc.
func (mock *PersistenceMock) LoadJobs() ([]persistence.JobInfo, error) {
	if mock.LoadJobsFunc == nil {
		panic("PersistenceMock.LoadJobsFunc: method is nil but Persistence.LoadJobs was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoadJobs.Lock()
	mock.calls.LoadJobs = append(mock.calls.LoadJobs, callInfo)
	mock.lockLoadJobs.Unlock()
	return mock.LoadJobsFunc()
}

// LoadJobsCalls gets all the calls that were made to LoadJobs.
// Check the length with:
//
//	len(mockedPersistence.LoadJobsCalls())
func (mock *PersistenceMock) LoadJobsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoadJobs.RLock()
	calls = mock.calls.LoadJobs
	mock.lockLoadJobs.RUnlock()
	return calls
}

// RecordExecution calls RecordExecutionFunc.
func (mock *PersistenceMock) RecordExecution(req request.RecordExecution) error {
	if mock.RecordExecutionFunc == nil {
		panic("PersistenceMock.RecordExecutionFunc: method is nil but Persistence.RecordExecution was just called")
	}
	callInfo := struct {
		Req request.RecordExecution
	}{
		Req: req,
	}
	mock.lockRecordExecution.Lock()
	mock.calls.RecordExecution = append(mock.calls.RecordExecution, callInfo)
	mock.lockRecordExecution.Unlock()
	return mock.RecordExecutionFunc(req)
}

// RecordExecutionCalls gets all the calls that were made to RecordExecution.
// Check the length with:
//
//	len(mockedPersistence.RecordExecutionCalls())
func (mock *PersistenceMock) RecordExecutionCalls() []struct {
	Req request.RecordExecution
} {
	var calls []struct {
		Req request.RecordExecution
	}
	mock.lockRecordExecution.RLock()
	calls = mock.calls.RecordExecution
	mock.lockRecordExecution.RUnlock()
	return calls
}

// SaveJobs calls SaveJobsFunc.
func (mock *PersistenceMock) SaveJobs(jobs []persistence.JobInfo) error {
	if mock.SaveJobsFunc == nil {
		panic("PersistenceMock.SaveJobsFunc: method is nil but Persistence.SaveJobs was just called")
	}
	callInfo := struct {
		Jobs []persistence.JobInfo
	}{
		Jobs: jobs,
	}
	mock.lockSaveJobs.Lock()
	mock.calls.SaveJobs = append(mock.calls.SaveJobs, callInfo)
	mock.lockSaveJobs.Unlock()
	return mock.SaveJobsFunc(jobs)
}

// SaveJobsCalls gets all the calls that were made to SaveJobs.
// Check the length with:
//
//	len(mockedPersistence.SaveJobsCalls())
func (mock *PersistenceMock) SaveJobsCalls() []struct {
	Jobs []persistence.JobInfo
} {
	var calls []struct {
		Jobs []persistence.JobInfo
	}
	mock.lockSaveJobs.RLock()
	calls = mock.calls.SaveJobs
	mock.lockSaveJobs.RUnlock()
	return calls
}
